=== geotools/geotools/modules/unsupported/arcgis-rest/src/main/resources/schema/services/feature/featureserver.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "currentVersion": {
      "type": "number"
    },
    "serviceItemId": {
      "type": "string"
    },
    "serviceDescription": {
      "type": "string"
    },
    "hasVersionedData": {
      "type": "boolean"
    },
    "supportsDisconnectedEditing": {
      "type": "boolean"
    },
    "hasStaticData": {
      "type": "boolean"
    },
    "maxRecordCount": {
      "type": "integer"
    },
    "supportedQueryFormats": {
      "type": "string"
    },
    "capabilities": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "copyrightText": {
      "type": "string"
    },
    "spatialReference": {
      "type": "object",
      "properties": {
        "wkid": {
          "type": "integer"
        },
        "latestWkid": {
          "type": "integer"
        },
        "wkt": {
          "type": "string"
        }
      },
      "required": [
        "wkid",
        "latestWkid"
      ]
    },
    "initialExtent": {
      "type": "object",
      "properties": {
        "xmin": {
          "type": "number"
        },
        "ymin": {
          "type": "number"
        },
        "xmax": {
          "type": "number"
        },
        "ymax": {
          "type": "number"
        },
        "spatialReference": {
          "type": "object",
          "properties": {
            "wkid": {
              "type": "integer"
            },
            "latestWkid": {
              "type": "integer"
            },
            "wkt": {
              "type": "string"
            }
          },
          "required": [
            "wkid",
            "latestWkid"
          ]
        }
      },
      "required": [
        "xmin",
        "ymin",
        "xmax",
        "ymax",
        "spatialReference"
      ]
    },
    "fullExtent": {
      "type": "object",
      "properties": {
        "xmin": {
          "type": "number"
        },
        "ymin": {
          "type": "number"
        },
        "xmax": {
          "type": "number"
        },
        "ymax": {
          "type": "number"
        },
        "spatialReference": {
          "type": "object",
          "properties": {
            "wkid": {
              "type": "integer"
            },
            "latestWkid": {
              "type": "integer"
            },
            "wkt": {
              "type": "string"
            }
          },
          "required": [
            "wkid",
            "latestWkid"
          ]
        }
      },
      "required": [
        "xmin",
        "ymin",
        "xmax",
        "ymax",
        "spatialReference"
      ]
    },
    "allowGeometryUpdates": {
      "type": "boolean"
    },
    "units": {
      "type": "string"
    },
    "size": {
      "type": "integer"
    },
    "syncEnabled": {
      "type": "boolean"
    },
    "syncCapabilities": {
      "type": "object",
      "properties": {
        "supportsAsync": {
          "type": "boolean"
        },
        "supportsRegisteringExistingData": {
          "type": "boolean"
        },
        "supportsSyncDirectionControl": {
          "type": "boolean"
        },
        "supportsPerLayerSync": {
          "type": "boolean"
        },
        "supportsPerReplicaSync": {
          "type": "boolean"
        },
        "supportsSyncModelNone": {
          "type": "boolean"
        },
        "supportsRollbackOnFailure": {
          "type": "boolean"
        },
        "supportsAttachmentsSyncDirection": {
          "type": "boolean"
        }
      },
      "required": [
        "supportsAsync",
        "supportsRegisteringExistingData",
        "supportsSyncDirectionControl",
        "supportsPerLayerSync",
        "supportsPerReplicaSync",
        "supportsSyncModelNone",
        "supportsRollbackOnFailure",
        "supportsAttachmentsSyncDirection"
      ]
    },
    "supportsApplyEditsWithGlobalIds": {
      "type": "boolean"
    },
    "editorTrackingInfo": {
      "type": "object",
      "properties": {
        "enableEditorTracking": {
          "type": "boolean"
        },
        "enableOwnershipAccessControl": {
          "type": "boolean"
        },
        "allowOthersToQuery": {
          "type": "boolean"
        },
        "allowOthersToUpdate": {
          "type": "boolean"
        },
        "allowOthersToDelete": {
          "type": "boolean"
        },
        "allowAnonymousToUpdate": {
          "type": "boolean"
        },
        "allowAnonymousToDelete": {
          "type": "boolean"
        }
      },
      "required": [
        "enableEditorTracking",
        "enableOwnershipAccessControl",
        "allowOthersToQuery",
        "allowOthersToUpdate",
        "allowOthersToDelete",
        "allowAnonymousToUpdate",
        "allowAnonymousToDelete"
      ]
    },
    "xssPreventionInfo": {
      "type": "object",
      "properties": {
        "xssPreventionEnabled": {
          "type": "boolean"
        },
        "xssPreventionRule": {
          "type": "string"
        },
        "xssInputRule": {
          "type": "string"
        }
      },
      "required": [
        "xssPreventionEnabled",
        "xssPreventionRule",
        "xssInputRule"
      ]
    },
    "layers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "parentLayerId": {
            "type": "integer"
          },
          "defaultVisibility": {
            "type": "boolean"
          },
          "subLayerIds": {
            "type": "null"
          },
          "minScale": {
            "type": "integer"
          },
          "maxScale": {
            "type": "integer"
          }
        },
        "required": [
          "id",
          "name",
          "parentLayerId",
          "defaultVisibility",
          "subLayerIds",
          "minScale",
          "maxScale"
        ]
      }
    },
    "tables": {
      "type": "array",
      "items": {}
    }
  },
  "required": [
    "currentVersion",
    "serviceItemId",
    "serviceDescription",
    "hasVersionedData",
    "supportsDisconnectedEditing",
    "hasStaticData",
    "maxRecordCount",
    "supportedQueryFormats",
    "capabilities",
    "description",
    "copyrightText",
    "spatialReference",
    "initialExtent",
    "fullExtent",
    "allowGeometryUpdates",
    "units",
    "size",
    "syncEnabled",
    "syncCapabilities",
    "supportsApplyEditsWithGlobalIds",
    "editorTrackingInfo",
    "xssPreventionInfo",
    "layers",
    "tables"
  ]
}

=== geotools/geotools/modules/unsupported/arcgis-rest/src/test/resources/org/geotools/data/arcgisrest/test-data/FeatureServerAirport.json
{
  "currentVersion" : 10.41,
  "serviceItemId" : "8e2fe1ee979b4c80a837caac2968d6d4",
  "serviceDescription" : "",
  "hasVersionedData" : false,
  "supportsDisconnectedEditing" : false,
  "hasStaticData" : true,
  "maxRecordCount" : 2000,
  "supportedQueryFormats" : "JSON",
  "capabilities" : "Query,Sync",
  "description" : "",
  "copyrightText" : "",
  "spatialReference" : {
    "wkid" : 102100,
    "latestWkid" : 3857
  },
  "initialExtent" : {
    "xmin" : -19496009.707956623,
    "ymin" : -7128878.350037612,
    "xmax" : 19947945.358478159,
    "ymax" : 14502137.593437815,
    "spatialReference" : {
      "wkid" : 102100,
      "latestWkid" : 3857
    }
  },
  "fullExtent" : {
    "xmin" : -19496009.707956623,
    "ymin" : -7128878.350037612,
    "xmax" : 19947945.358478159,
    "ymax" : 14502137.593437815,
    "spatialReference" : {
      "wkid" : 102100,
      "latestWkid" : 3857
    }
  },
  "allowGeometryUpdates" : true,
  "units" : "esriMeters",
  "size" : 434176,
  "syncEnabled" : true,
  "syncCapabilities" : {
    "supportsAsync" : true,
    "supportsRegisteringExistingData" : true,
    "supportsSyncDirectionControl" : true,
    "supportsPerLayerSync" : true,
    "supportsPerReplicaSync" : true,
    "supportsSyncModelNone" : true,
    "supportsRollbackOnFailure" : true,
    "supportsAttachmentsSyncDirection" : true
  },
  "supportsApplyEditsWithGlobalIds" : true,
  "editorTrackingInfo" : {
    "enableEditorTracking" : false,
    "enableOwnershipAccessControl" : false,
    "allowOthersToQuery" : true,
    "allowOthersToUpdate" : true,
    "allowOthersToDelete" : true,
    "allowAnonymousToUpdate" : true,
    "allowAnonymousToDelete" : true
  },
  "xssPreventionInfo" : {
    "xssPreventionEnabled" : true,
    "xssPreventionRule" : "InputOnly",
    "xssInputRule" : "rejectInvalid"
  },
  "layers" : [ {
    "id" : 0,
    "name" : "Airports_2",
    "parentLayerId" : -1,
    "defaultVisibility" : true,
    "subLayerIds" : null,
    "minScale" : 0,
    "maxScale" : 0
  } , {
    "id" : 1,
    "name" : "Airports_3",
    "parentLayerId" : -1,
    "defaultVisibility" : true,
    "subLayerIds" : null,
    "minScale" : 0,
    "maxScale" : 0
  } ],
  "tables" : []
}
