=== geotools/geotools/modules/unsupported/arcgis-rest/src/main/resources/schema/catalog/catalog.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://project-open-data.cio.gov/v1.1/schema/catalog.json#",
  "title": "Project Open Data Catalog",
  "description": "Validates an entire collection of Project Open Data metadata JSON objects. Agencies produce said collections in the form of Data.json files.",
  "type": "object",
  "dependencies": {
    "@type": [
      "@context"
    ]
  },
  "required": [
    "conformsTo",
    "dataset"
  ],
  "properties": {
    "@context": {
      "title": "Metadata Context",
      "description": "URL or JSON object for the JSON-LD Context that defines the schema used",
      "type": "string",
      "format": "uri"
    },
    "@id": {
      "title": "Metadata Catalog ID",
      "description": "IRI for the JSON-LD Node Identifier of the Catalog. This should be the URL of the data.json file itself.",
      "type": "string",
      "format": "uri"
    },
    "@type": {
      "title": "Metadata Context",
      "description": "IRI for the JSON-LD data type. This should be dcat:Catalog for the Catalog",
      "enum": [
        "dcat:Catalog"
      ]
    },
    "conformsTo": {
      "description": "Version of Schema",
      "title": "Version of Schema",
      "enum": [
        "https://project-open-data.cio.gov/v1.1/schema"
      ]
    },
    "describedBy": {
      "description": "URL for the JSON Schema file that defines the schema used",
      "title": "Data Dictionary",
      "type": "string",
      "format": "uri"
    },
    "dataset": {
      "type": "array",
      "items": {
        "$ref": "dataset.json",
        "minItems": 1,
        "uniqueItems": true
      }
    }
  }
}

=== geotools/geotools/modules/unsupported/arcgis-rest/src/test/resources/org/geotools/data/arcgisrest/test-data/catalog.json
{
  "@context" : "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@type" : "dcat:Catalog",
  "conformsTo" : "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy" : "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "dataset" : [ {
    "@type" : "dcat:Dataset",
    "identifier" : "http://data.dhs.opendata.arcgis.com/datasets/940854a3f46345f5af7d5c61abce6ec2_0",
    "title" : "LGA Profile 2014 (beta)",
    "description" : "<div>2014 Local Government Area Profiles</div><div><br /></div>https://www2.health.vic.gov.au/about/reporting-planning-data/gis-and-planning-products/geographical-profiles<div>&gt; Please read the data definistions at the link above</div><div>&gt; xls and pdf documents area available at the link above</div><div>&gt; This is a beta release of the 2014 LGA profiles in this format. Field names and types may change during the beta phase.Â </div><div><br /></div><div>Last updated : 24 May 2016</div><div>Owning agency : Department of Health and Human Services, Victoria</div><div>Copyright statement : https://www.health.vic.gov.au/copyright</div><div>Licence name : https://www.health.vic.gov.au/data-license</div><div>Disclaimer: https://www.health.vic.gov.au/data-disclaimer</div><div>Attribution statement: https://www.health.vic.gov.au/data-attribution</div><div><br /></div><div>Off-line access : Department of Health and Human Services, GPO Box 4057, Melbourne Victoria, 3001</div><div><br /></div><div>Geographic coverage-jurisdiction : Victoria</div>",
    "keyword" : [ "LGA Profiles", "Health and Human Services", "LGA" ],
    "issued" : "2016-07-27T04:55:30.000Z",
    "modified" : "2016-08-12T18:56:09.724Z",
    "publisher" : {
      "name" : "Health and Human Services Victoria"
    },
    "contactPoint" : {
      "@type" : "vcard:Contact",
      "fn" : "miles da costa",
      "hasEmail" : "mailto:spatial@dhhs.vic.gov.au"
    },
    "accessLevel" : "public",
    "distribution" : [
        {
          "@type" : "dcat:Distribution",
          "title" : "ArcGIS Open Dataset",
          "format" : "Web page",
          "mediaType" : "text/html",
          "accessURL" : "http://data.dhs.opendata.arcgis.com/datasets/940854a3f46345f5af7d5c61abce6ec2_0"
        },
        {
          "@type" : "dcat:Distribution",
          "title" : "Esri Rest API",
          "format" : "Esri REST",
          "mediaType" : "application/json",
          "accessURL" : "https://services.arcgis.com/B7qHofahIc9hrOqB/arcgis/rest/services/LGA_Profile_2014_(beta)/FeatureServer/0"
        },
        {
          "@type" : "dcat:Distribution",
          "title" : "GeoJSON",
          "format" : "GeoJSON",
          "mediaType" : "application/vnd.geo+json",
          "downloadURL" : "http://data.dhs.opendata.arcgis.com/datasets/940854a3f46345f5af7d5c61abce6ec2_0.geojson"
        },
        {
          "@type" : "dcat:Distribution",
          "title" : "CSV",
          "format" : "CSV",
          "mediaType" : "text/csv",
          "downloadURL" : "http://data.dhs.opendata.arcgis.com/datasets/940854a3f46345f5af7d5c61abce6ec2_0.csv"
        },
        {
          "@type" : "dcat:Distribution",
          "title" : "KML",
          "format" : "KML",
          "mediaType" : "application/vnd.google-earth.kml+xml",
          "downloadURL" : "http://data.dhs.opendata.arcgis.com/datasets/940854a3f46345f5af7d5c61abce6ec2_0.kml"
        },
        {
          "@type" : "dcat:Distribution",
          "title" : "Shapefile",
          "format" : "ZIP",
          "mediaType" : "application/zip",
          "downloadURL" : "http://data.dhs.opendata.arcgis.com/datasets/940854a3f46345f5af7d5c61abce6ec2_0.zip"
        } ],
    "landingPage" : "http://data.dhs.opendata.arcgis.com/datasets/940854a3f46345f5af7d5c61abce6ec2_0",
    "webService" : "https://services.arcgis.com/B7qHofahIc9hrOqB/arcgis/rest/services/LGA_Profile_2014_(beta)/FeatureServer/0",
    "license" : "http://data.dhs.opendata.arcgis.com/datasets/940854a3f46345f5af7d5c61abce6ec2_0/license.json",
    "spatial" : "140.68687930094052,-39.14445967968202,150.07953385695868,-33.95278976659559",
    "theme" : [ "geospatial" ]
  } ]
}

=== geotools/geotools/modules/unsupported/arcgis-rest/src/test/resources/org/geotools/data/arcgisrest/test-data/wsServiceInDistribution.json
{
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@type": "dcat:Catalog",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "dataset": [
    {
      "@type": "dcat:Dataset",
      "identifier": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0",
      "webService" : "https://services.arcgis.com/B7qHofahIc9hrOqB/arcgis/rest/services/LGA_Profile_2014_(beta)/FeatureServer/0",
      "license": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0/license.json",
      "landingPage": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0",
      "title": "ERROR",
      "description": "These links are used to calculate travel time for Bluetooth live data.  <br /><div><span style='line-height: 26.35px;'><a href='http://data.vicroads.vic.gov.au/metadata/Bluetooth_Links - Open Data.html' target='_blank'>About this dataset</a>  </span><a href='mailto:SISSupport@roads.vic.gov.au' style='line-height: 26.35px;' target='_blank'>Contact Us</a><br /></div>",
      "keyword": [
        "Bluetooth",
        "VicRoads Open Data",
        "Road Assets Open Data",
        "Electrical",
        "Sites"
      ],
      "issued": "2017-07-25T06:26:10.000Z",
      "modified": "2017-07-26T07:11:28.000Z",
      "publisher": {
        "source": "VicRoads"
      },
      "contactPoint": {
        "@type": "vcard:Contact",
        "fn": "VicRoads"
      },
      "accessLevel": "public",
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "title": "ArcGIS Hub Dataset",
          "format": "Web Page",
          "mediaType": "text/html",
          "accessURL": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0"
        }
      ],
      "spatial": "144.623,-38.3995,145.3766,-37.6697",
      "theme": [
        "geospatial"
      ]
    },
    {
      "@type": "dcat:Dataset",
      "identifier": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0",
      "webService" : "https://services.arcgis.com/B7qHofahIc9hrOqB/arcgis/rest/services/LGA_Profile_2014_(beta)/FeatureServer/0",
      "license": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0/license.json",
      "landingPage": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0",
      "title": "ERROR",
      "description": "These links are used to calculate travel time for Bluetooth live data.  <br /><div><span style='line-height: 26.35px;'><a href='http://data.vicroads.vic.gov.au/metadata/Bluetooth_Links - Open Data.html' target='_blank'>About this dataset</a>  </span><a href='mailto:SISSupport@roads.vic.gov.au' style='line-height: 26.35px;' target='_blank'>Contact Us</a><br /></div>",
      "keyword": [
        "Bluetooth",
        "VicRoads Open Data",
        "Road Assets Open Data",
        "Electrical",
        "Sites"
      ],
      "issued": "2017-07-25T06:26:10.000Z",
      "modified": "2017-07-26T07:11:28.000Z",
      "publisher": {
        "source": "VicRoads"
      },
      "contactPoint": {
        "@type": "vcard:Contact",
        "fn": "VicRoads"
      },
      "accessLevel": "public",
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "title": "ArcGIS Hub Dataset",
          "format": "Web Page",
          "mediaType": "text/html",
          "accessURL": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0"
        }
      ],
      "spatial": "144.623,-38.3995,145.3766,-37.6697",
      "theme": [
        "geospatial"
      ]
    },
    {
      "@type": "dcat:Dataset",
      "identifier": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_1",
      "license": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0/license.json",
      "landingPage": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0",
      "title": "Bluetooth Links 1",
      "description": "These links are used to calculate travel time for Bluetooth live data.  <br /><div><span style='line-height: 26.35px;'><a href='http://data.vicroads.vic.gov.au/metadata/Bluetooth_Links - Open Data.html' target='_blank'>About this dataset</a>  </span><a href='mailto:SISSupport@roads.vic.gov.au' style='line-height: 26.35px;' target='_blank'>Contact Us</a><br /></div>",
      "keyword": [
        "Bluetooth",
        "VicRoads Open Data",
        "Road Assets Open Data",
        "Electrical",
        "Sites"
      ],
      "issued": "2017-07-25T06:26:10.000Z",
      "modified": "2017-07-26T07:11:28.000Z",
      "publisher": {
        "source": "VicRoads"
      },
      "contactPoint": {
        "@type": "vcard:Contact",
        "fn": "VicRoads"
      },
      "accessLevel": "public",
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "title": "Esri Rest API",
          "format": "Esri REST",
          "mediaType": "application/json",
          "accessURL": "https://services2.arcgis.com/18ajPSI0b3ppsmMt/arcgis/rest/services/ERROR/FeatureServer/0"
        }
      ],
      "spatial": "144.623,-38.3995,145.3766,-37.6697",
      "theme": [
        "geospatial"
      ]
    },
    {
      "@type": "dcat:Dataset",
      "identifier": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_2",
      "license": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0/license.json",
      "landingPage": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0",
      "title": "Bluetooth Links 2",
      "description": "These links are used to calculate travel time for Bluetooth live data.  <br /><div><span style='line-height: 26.35px;'><a href='http://data.vicroads.vic.gov.au/metadata/Bluetooth_Links - Open Data.html' target='_blank'>About this dataset</a>  </span><a href='mailto:SISSupport@roads.vic.gov.au' style='line-height: 26.35px;' target='_blank'>Contact Us</a><br /></div>",
      "keyword": [
        "Bluetooth",
        "VicRoads Open Data",
        "Road Assets Open Data",
        "Electrical",
        "Sites"
      ],
      "issued": "2017-07-25T06:26:10.000Z",
      "modified": "2017-07-26T07:11:28.000Z",
      "publisher": {
        "source": "VicRoads"
      },
      "contactPoint": {
        "@type": "vcard:Contact",
        "fn": "VicRoads"
      },
      "accessLevel": "public",
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "title": "Esri Rest API",
          "format": "Esri REST",
          "mediaType": "application/json",
          "accessURL": "https://services2.arcgis.com/18ajPSI0b3ppsmMt/arcgis/rest/services/Bluetooth_Links_v2/FeatureServer/0"
        }
      ],
      "spatial": "144.623,-38.3995,145.3766,-37.6697",
      "theme": [
        "geospatial"
      ]
    },
    {
      "@type": "dcat:Dataset",
      "identifier": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_3",
      "license": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0/license.json",
      "landingPage": "http://vicroadsopendata-vicroadsmaps.opendata.arcgis.com/datasets/bfeadc0fb0a44c6e8ab3a17c76e5a562_0",
      "title": "ERROR NO DISTRIBUTION ACCESS URL",
      "description": "These links are used to calculate travel time for Bluetooth live data.  <br /><div><span style='line-height: 26.35px;'><a href='http://data.vicroads.vic.gov.au/metadata/Bluetooth_Links - Open Data.html' target='_blank'>About this dataset</a>  </span><a href='mailto:SISSupport@roads.vic.gov.au' style='line-height: 26.35px;' target='_blank'>Contact Us</a><br /></div>",
      "keyword": [
        "Bluetooth",
        "VicRoads Open Data",
        "Road Assets Open Data",
        "Electrical",
        "Sites"
      ],
      "issued": "2017-07-25T06:26:10.000Z",
      "modified": "2017-07-26T07:11:28.000Z",
      "publisher": {
        "source": "VicRoads"
      },
      "contactPoint": {
        "@type": "vcard:Contact",
        "fn": "VicRoads"
      },
      "accessLevel": "public",
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "title": "Esri Rest API",
          "format": "Esri REST",
          "mediaType": "application/json"
        }
      ],
      "spatial": "144.623,-38.3995,145.3766,-37.6697",
      "theme": [
        "geospatial"
      ]
    }

  ]
}
